
export const dashboardStudentCourseModule = [
  {
    id: 1,
    title: 'Data Programming',
    dateRange: '11 Apr - 17 Apr',
    progress: 60,
    totalItems: '3/7 Item',
    liveClasses: 2,
    assignments: 1,
    tests: 2,
    status: 'Finished',
  },
  {
    id: 2,
    title: 'Web Development',
    dateRange: '18 Apr - 24 Apr',
    progress: 40,
    totalItems: '2/5 Item',
    liveClasses: 1,
    assignments: 2,
    tests: 1,
    status: 'Ongoing',
  },
  {
    id: 3,
    title: 'Database Design',
    dateRange: '25 Apr - 1 May',
    progress: 75,
    totalItems: '6/8 Item',
    liveClasses: 3,
    assignments: 1,
    tests: 1,
    status: 'Finished',
  },
  {
    id: 4,
    title: 'Machine Learning',
    dateRange: '2 May - 8 May',
    progress: 50,
    totalItems: '4/8 Item',
    liveClasses: 2,
    assignments: 2,
    tests: 2,
    status: 'Ongoing',
  },
  {
    id: 5,
    title: 'Cloud Computing',
    dateRange: '9 May - 15 May',
    progress: 30,
    totalItems: '2/6 Item',
    liveClasses: 1,
    assignments: 1,
    tests: 1,
    status: 'Pending',
  },
  {
    id: 6,
    title: 'Cyber Security',
    dateRange: '16 May - 22 May',
    progress: 90,
    totalItems: '9/10 Item',
    liveClasses: 4,
    assignments: 1,
    tests: 2,
    status: 'Finished',
  },
];